name: Sync Fork with Upstream

on:
  # Run daily at 3am
  schedule:
    - cron: '0 10 * * *'

  # Allow manual triggering
  workflow_dispatch:

jobs:
  sync:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Setup Upstream Remote
        run: |
          if git remote | grep -q "^upstream$"; then
            echo "Upstream remote already exists, updating URL"
            git remote set-url upstream https://github.com/danny-avila/LibreChat.git
          else
            echo "Adding upstream remote"
            git remote add upstream https://github.com/danny-avila/LibreChat.git
          fi
          git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git checkout main
          git merge upstream/main

      - name: Push Changes
        run: |
          git push origin main
